services:
  - type: web
    name: recycleai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run RecycleAI-main/app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: false 