[server]
address = "0.0.0.0"
port = 10000
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200

[browser]
serverAddress = "0.0.0.0"
serverPort = 10000
gatherUsageStats = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"